// <auto-generated />
using System;
using IMEAutomationDBOperations.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KonyaTeknikÜniversitesi_IMEOtomasyonu.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260613150430_ProfessionalArchitecture")]
    partial class ProfessionalArchitecture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IMEAutomationDBOperations.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankIbanNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeCount")
                        .HasColumnType("int");

                    b.Property<string>("Industry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies", (string)null);

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            Address = "ODTÜ Teknokent, Ankara",
                            CompanyName = "TechCorp Yazılım A.Ş.",
                            Email = "info@techcorp.com",
                            Industry = "Bilişim",
                            PhoneNumber = "03125555555",
                            TaxNumber = "1234567890"
                        });
                });

            modelBuilder.Entity("IMEAutomationDBOperations.Models.Internship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommissionFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstructorFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeaveDays")
                        .HasColumnType("int");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalTrainingDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkDays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StudentId");

                    b.ToTable("Internships", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaveDays = 0,
                            PaidAmount = 0m,
                            StartDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 4,
                            StudentId = 1,
                            SupervisorId = 2,
                            Title = "Full-Stack Web Geliştirme Stajı",
                            TotalTrainingDays = 60,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkDays = "Pazartesi-Salı-Çarşamba-Perşembe-Cuma"
                        });
                });

            modelBuilder.Entity("IMEAutomationDBOperations.Models.InternshipEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceScore")
                        .HasColumnType("int");

                    b.Property<int>("CommunicationScore")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentUsageScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpressionScore")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InternshipId")
                        .HasColumnType("int");

                    b.Property<int>("KnowledgeScore")
                        .HasColumnType("int");

                    b.Property<int>("MotivationScore")
                        .HasColumnType("int");

                    b.Property<int>("ProblemSolvingScore")
                        .HasColumnType("int");

                    b.Property<int>("ReportingScore")
                        .HasColumnType("int");

                    b.Property<int>("ResponsibilityScore")
                        .HasColumnType("int");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<int>("TeamworkScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InternshipId")
                        .IsUnique();

                    b.HasIndex("SupervisorId");

                    b.ToTable("InternshipEvaluations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttendanceScore = 95,
                            CommunicationScore = 0,
                            EquipmentUsageScore = 0,
                            EvaluatedAt = new DateTime(2023, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpressionScore = 0,
                            InternshipId = 1,
                            KnowledgeScore = 85,
                            MotivationScore = 0,
                            ProblemSolvingScore = 0,
                            ReportingScore = 0,
                            ResponsibilityScore = 90,
                            SupervisorId = 2,
                            TeamworkScore = 0
                        });
                });

            modelBuilder.Entity("IMEAutomationDBOperations.Models.InternshipSupervisor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Expertise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("InternshipSupervisors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Expertise = "Kıdemli Yazılım Geliştirici",
                            PhoneNumber = "05321234567",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("IMEAutomationDBOperations.Models.Note", b =>
                {
                    b.Property<int>("NoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<string>("SubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("NoteID");

                    b.HasIndex("StudentID");

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("IMEAutomationDBOperations.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcademicYear = 4,
                            Address = "Selçuklu, Konya",
                            BirthDate = new DateTime(2000, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Bilgisayar Mühendisliği",
                            NationalID = "12345678901",
                            PhoneNumber = "05551234567",
                            SchoolNumber = "191234567",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("IMEAutomationDBOperations.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmet.yavuz@konyateknik.edu.tr",
                            FirstName = "Ahmet",
                            IsActive = true,
                            LastName = "Yavuz",
                            PasswordHash = "$2a$11$e/R/i.k2yN.Y3d7pTzG02evK./5QGk7v/3x2s5X0Z8a",
                            Role = 2,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ayse.demir@techcorp.com",
                            FirstName = "Ayşe",
                            IsActive = true,
                            LastName = "Demir",
                            PasswordHash = "$2a$11$e/R/i.k2yN.Y3d7pTzG02evK./5QGk7v/3x2s5X0Z8a",
                            Role = 3,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "komisyon@konyateknik.edu.tr",
                            FirstName = "Komisyon",
                            IsActive = true,
                            LastName = "Başkanı",
                            PasswordHash = "$2a$11$e/R/i.k2yN.Y3d7pTzG02evK./5QGk7v/3x2s5X0Z8a",
                            Role = 4,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("IMEAutomationDBOperations.Models.Video", b =>
                {
                    b.Property<int>("VideoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideoID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VideoID");

                    b.HasIndex("StudentID");

                    b.ToTable("Videos", (string)null);
                });

            modelBuilder.Entity("IMEAutomationDBOperations.Models.Internship", b =>
                {
                    b.HasOne("IMEAutomationDBOperations.Models.Company", "Company")
                        .WithMany("Internships")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IMEAutomationDBOperations.Models.Student", "Student")
                        .WithMany("Internships")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("IMEAutomationDBOperations.Models.InternshipEvaluation", b =>
                {
                    b.HasOne("IMEAutomationDBOperations.Models.Internship", "Internship")
                        .WithOne("Evaluation")
                        .HasForeignKey("IMEAutomationDBOperations.Models.InternshipEvaluation", "InternshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMEAutomationDBOperations.Models.InternshipSupervisor", "Supervisor")
                        .WithMany("Evaluations")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Internship");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("IMEAutomationDBOperations.Models.InternshipSupervisor", b =>
                {
                    b.HasOne("IMEAutomationDBOperations.Models.Company", "Company")
                        .WithMany("Supervisors")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IMEAutomationDBOperations.Models.User", "User")
                        .WithOne("SupervisorDetails")
                        .HasForeignKey("IMEAutomationDBOperations.Models.InternshipSupervisor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IMEAutomationDBOperations.Models.Note", b =>
                {
                    b.HasOne("IMEAutomationDBOperations.Models.Student", "Student")
                        .WithMany("Notes")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("IMEAutomationDBOperations.Models.Student", b =>
                {
                    b.HasOne("IMEAutomationDBOperations.Models.User", "User")
                        .WithOne("StudentDetails")
                        .HasForeignKey("IMEAutomationDBOperations.Models.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IMEAutomationDBOperations.Models.Video", b =>
                {
                    b.HasOne("IMEAutomationDBOperations.Models.Student", "Student")
                        .WithMany("Videos")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("IMEAutomationDBOperations.Models.Company", b =>
                {
                    b.Navigation("Internships");

                    b.Navigation("Supervisors");
                });

            modelBuilder.Entity("IMEAutomationDBOperations.Models.Internship", b =>
                {
                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("IMEAutomationDBOperations.Models.InternshipSupervisor", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("IMEAutomationDBOperations.Models.Student", b =>
                {
                    b.Navigation("Internships");

                    b.Navigation("Notes");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("IMEAutomationDBOperations.Models.User", b =>
                {
                    b.Navigation("StudentDetails");

                    b.Navigation("SupervisorDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
